name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create Firebase Config JSON
      run: echo "$FIREBASE_CONFIG" > app/google-services.json
    - name: Build with Gradle
      run: ./gradlew build -x test

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create Firebase Config JSON
        run: echo "$FIREBASE_CONFIG" > app/google-services.json
      - name: Run Unit Tests
        run: ./gradlew test

  deploy:
    if: github.event_name == 'workflow_dispatch'
    needs: test
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create Firebase Config JSON
        run: echo "$FIREBASE_CONFIG" > app/google-services.json
      - name: Create Firebase Service Account JSON
        run: echo "$FIREBASE_SERVICE_CREDENTIALS" > firebase-service-account.json
      - name: Build and Deploy
        run: ./gradlew assembleDebug appDistributionUploadDebug

